var animations = [
  [
    {
      id: "#i01",
      duration: 250,
      delayBefore: 250,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i02",
      duration: 750,
      delayBefore: 350,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i03",
      duration: 750,
      delayBefore: 450,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i03-1",
      duration: 750,
      delayBefore: 550,
      delayAfter: 3000,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
  ],
  [
    {
      id: "#i03-1",
      duration: 750,
      delayBefore: 0,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, left: "20%", top: 0 },
    },
    {
      id: "#i03",
      duration: 750,
      delayBefore: 100,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, left: "20%", top: 0 },
    },
  ],
  [
    {
      id: "#i04",
      duration: 750,
      delayBefore: 250,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i04-1",
      duration: 750,
      delayBefore: 350,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i04-2",
      duration: 750,
      delayBefore: 450,
      delayAfter: 3000,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
  ],
  [
    {
      id: "#i04-2",
      duration: 750,
      delayBefore: 0,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, left: "20%", top: 0 },
    },
    {
      id: "#i04-1",
      duration: 750,
      delayBefore: 100,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, left: "20%", top: 0 },
    },
    {
      id: "#i04",
      duration: 750,
      delayBefore: 200,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, left: "20%", top: 0 },
    },
  ],
  [
    {
      id: "#i05",
      duration: 750,
      delayBefore: 250,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i05-1",
      duration: 750,
      delayBefore: 350,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i05-2",
      duration: 750,
      delayBefore: 450,
      delayAfter: 3000,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
  ],
  [
    {
      id: "#i05-2",
      duration: 750,
      delayBefore: 0,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, left: "20%", top: 0 },
    },
    {
      id: "#i05-1",
      duration: 750,
      delayBefore: 100,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, left: "20%", top: 0 },
    },
    {
      id: "#i05",
      duration: 750,
      delayBefore: 200,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, left: "20%", top: 0 },
    },
    {
      id: "#i02",
      duration: 250,
      delayBefore: 200,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, left: 0, top:"10%" },
    },
  ],
  [
    {
      id: "#i06",
      duration: 750,
      delayBefore: 250,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i07",
      duration: 750,
      delayBefore: 450,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i08",
      duration: 750,
      delayBefore: 650,
      delayAfter: 3000,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
  ],
];
new WAnimation(animations, {
  loop: false,
  clearAfterEnd: false,
}).startAnimation();
