var animations = [
  [
    {
      id: "#i01",
      duration: 250,
      delayBefore: 0,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1 },
    },
    {
      id: "#i02",
      duration: 750,
      delayBefore: 350,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i03",
      duration: 750,
      delayBefore: 450,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i03-1",
      duration: 750,
      delayBefore: 450,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i04",
      duration: 750,
      delayBefore: 850,
      delayAfter: 3000,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
  ],
  [
    {
      id: "#i02",
      duration: 350,
      delayBefore: 0,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, left: 0, top: "10%" },
    },
    {
      id: "#i03",
      duration: 350,
      delayBefore: 100,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, left: "-10%", top: 0 },
    },
    {
      id: "#i03-1",
      duration: 350,
      delayBefore: 100,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, left: "10%", top: 0 },
    },
    {
      id: "#i04",
      duration: 350,
      delayBefore: 100,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, left: 0, top: "10%" },
    },
  ],
  [
    {
      id: "#i05",
      duration: 750,
      delayBefore: 250,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i06",
      duration: 750,
      delayBefore: 350,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i07",
      duration: 750,
      delayBefore: 550,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i08",
      duration: 750,
      delayBefore: 650,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i09",
      duration: 750,
      delayBefore: 750,
      delayAfter: 3000,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
  ],
  [
    {
      id: "#i05",
      duration: 350,
      delayBefore: 0,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, left: "10%", top: "10%" },
    },
    {
      id: "#i06",
      duration: 350,
      delayBefore: 100,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, left: "-10%", top: "-10%" },
    },
    {
      id: "#i07",
      duration: 350,
      delayBefore: 300,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, left: 0, top: "20%" },
    },
    {
      id: "#i08",
      duration: 350,
      delayBefore: 200,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, left: 0, top: "20%" },
    },
  ],
  [
    {
      id: "#i09-1",
      duration: 750,
      delayBefore: 250,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i09-2",
      duration: 750,
      delayBefore: 300,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i10",
      duration: 750,
      delayBefore: 450,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
    {
      id: "#i11",
      duration: 750,
      delayBefore: 550,
      delayAfter: 3000,
      easing: "easeOutCubic",
      animations: { opacity: 1, left: 0, top: 0 },
    },
  ],
];
new WAnimation(animations, {
  loop: true,
  clearAfterEnd: false,
}).startAnimation();
