var animations = [
  [
    {
      id: "#i01",
      duration: 250,
      delayBefore: 100,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i02",
      duration: 300,
      delayBefore: 250,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i03",
      duration: 300,
      delayBefore: 450,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i04",
      duration: 300,
      delayBefore: 550,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i05",
      duration: 300,
      delayBefore: 650,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i06",
      duration: 300,
      delayBefore: 1050,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i06-1",
      duration: 300,
      delayBefore: 1150,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i06-2",
      duration: 300,
      delayBefore: 1250,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i06-3",
      duration: 300,
      delayBefore: 1350,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i06-4",
      duration: 300,
      delayBefore: 1450,
      delayAfter: 4000,
      animations: { opacity: 1, top: 0, left: 0 },
    },
  ],
  [
    {
      id: "#i03",
      duration: 500,
      delayBefore: 0,
      delayAfter: 0,
      animations: { opacity: 0, top: 0, left: 0 },
    },
    {
      id: "#i04",
      duration: 500,
      delayBefore: 0,
      delayAfter: 0,
      animations: { opacity: 0, top: 0, left: 0 },
    },
    {
      id: "#i05",
      duration: 500,
      delayBefore: 0,
      delayAfter: 0,
      animations: { opacity: 0, top: 0, left: 0 },
    },
    {
      id: "#i06",
      duration: 500,
      delayBefore: 0,
      delayAfter: 0,
      animations: { opacity: 0, top: 0, left: 0 },
    },
    {
      id: "#i06-1",
      duration: 500,
      delayBefore: 0,
      delayAfter: 0,
      animations: { opacity: 0, top: 0, left: 0 },
    },
    {
      id: "#i06-2",
      duration: 500,
      delayBefore: 0,
      delayAfter: 0,
      animations: { opacity: 0, top: 0, left: 0 },
    },
    {
      id: "#i06-3",
      duration: 500,
      delayBefore: 0,
      delayAfter: 0,
      animations: { opacity: 0, top: 0, left: 0 },
    },
    {
      id: "#i06-4",
      duration: 500,
      delayBefore: 0,
      delayAfter: 0,
      animations: { opacity: 0, top: 0, left: 0 },
    },
  ],
  [
    {
      id: "#i02-1",
      duration: 750,
      delayBefore: 250,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i10",
      duration: 750,
      delayBefore: 250,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i01-1",
      duration: 750,
      delayBefore: 250,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i11",
      duration: 750,
      delayBefore: 450,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i02-2",
      duration: 750,
      delayBefore: 250,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i12",
      duration: 750,
      delayBefore: 650,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i07",
      duration: 450,
      delayBefore: 950,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i08",
      duration: 450,
      delayBefore: 1050,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i09",
      duration: 450,
      delayBefore: 1150,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i13",
      duration: 450,
      delayBefore: 1350,
      delayAfter: 3000,
      animations: { opacity: 1, top: 0, left: 0 },
    },
  ],
  [
      {
      id: "#i14",
      duration: 250,
      delayBefore: 100,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i16",
      duration: 300,
      delayBefore: 250,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },  
    {
      id: "#i15",
      duration: 300,
      delayBefore: 550,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },  
    {
      id: "#i17",
      duration: 300,
      delayBefore: 750,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },  
    {
      id: "#i18",
      duration: 300,
      delayBefore: 850,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },  
    {
      id: "#i19",
      duration: 300,
      delayBefore: 950,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },  
    {
      id: "#i19-1",
      duration: 300,
      delayBefore: 1050,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },  
    {
      id: "#i19-2",
      duration: 300,
      delayBefore: 1150,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },  
    {
      id: "#i19-3",
      duration: 300,
      delayBefore: 1250,
      delayAfter: 0,
      animations: { opacity: 1, top: 0, left: 0 },
    },  
    {
      id: "#i20",
      duration: 300,
      delayBefore: 1350,
      delayAfter: 3000,
      animations: { opacity: 1, top: 0, left: 0 },
    },  
  ]
];
new WAnimation(animations, {
  loop: true,
  clearAfterEnd: false,
}).startAnimation();
